# Generated by Django 6.1 on 2026-09-01 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("positive", "Positivo"),
                            ("neutral", "Neutral"),
                            ("negative", "Negativo"),
                        ],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.5, help_text="0-1, donde 1 es muy positivo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analysis",
                        to="interactions.interaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["label"], name="analytics_s_label_ccf6d2_idx"),
                    models.Index(
                        fields=["created_at"], name="analytics_s_created_4f2163_idx"
                    ),
                ],
            },
        ),
    ]
