# Generated by Django 6.1 on 2026-09-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_company"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="tags.tag"
            ),
        ),
    ]
