# Generated by Django 6.1 on 2026-10-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contact_tags"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_contacts", to="products.product"
            ),
        ),
    ]
