# Generated by Django 6.1 on 2026-10-03 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_contact_interests"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="overdue_notified",
            field=models.BooleanField(
                default=False,
                help_text="Si ya se emitió la notificación de vencimiento",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["due_date", "overdue_notified"],
                name="tasks_task_due_dat_884594_idx",
            ),
        ),
    ]
