# Generated by Django 6.1 on 2026-09-21 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("technology", "Tecnología"),
                            ("retail", "Retail"),
                            ("finance", "Finanzas"),
                            ("health", "Salud"),
                            ("education", "Educación"),
                            ("manufacturing", "Manufactura"),
                            ("services", "Servicios"),
                            ("other", "Otra"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("startup", "Startup (1-10)"),
                            ("small", "Pequeña (11-50)"),
                            ("medium", "Mediana (51-200)"),
                            ("large", "Grande (201-1000)"),
                            ("enterprise", "Corporación (1000+)"),
                        ],
                        default="small",
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "annual_revenue",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Ingresos anuales estimados en CLP",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["industry"], name="companies_c_industr_6efa2c_idx"
                    ),
                    models.Index(fields=["size"], name="companies_c_size_71adf7_idx"),
                ],
            },
        ),
    ]
