# Generated by Django 6.1 on 2026-10-02 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("contacts", "0004_contact_interests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Valor estimado en CLP",
                        max_digits=12,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("discovery", "Descubrimiento"),
                            ("proposal", "Propuesta"),
                            ("negotiation", "Negociación"),
                            ("won", "Ganada"),
                            ("lost", "Perdida"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=0, help_text="Probabilidad de cierre (0-100)"
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("lost_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="companies.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["stage"], name="opportuniti_stage_58f90a_idx"),
                    models.Index(
                        fields=["assigned_to"], name="opportuniti_assigne_8cc172_idx"
                    ),
                    models.Index(
                        fields=["expected_close_date"],
                        name="opportuniti_expecte_c56295_idx",
                    ),
                    models.Index(
                        fields=["contact", "stage"],
                        name="opportuniti_contact_8762f4_idx",
                    ),
                ],
            },
        ),
    ]
